### ISSUE TITLE
Almost invisible buttons when using light mode

### ISSUE THREAD

**Issue by itsCryne** [nick-shmyrev/improved-osk-gnome-ext#12]
I currently use the extension on an HP Envy x360 with Pop!_OS 21.04, GNOME Shell 3.38.4 and Improved OSK 4.
When I switch to light mode however, some keys become almost invisible, as shown in the following picture:
![image](https://user-images.githubusercontent.com/51213332/141014723-e401ba79-2901-49f0-8c16-bc295ecedc86.png)

**Comment by nick-shmyrev** [comment]
Interesting, thanks for reporting this! I'll see if I can track the issue down.

**Comment by nick-shmyrev** [comment]
Sorry for the long wait, had a really busy couple of weeks. The gray key text color seems to be coming from the PopOS light theme. I've explicitly set non-alphanumeric keys text color to white, hopefully this would make them more readable. A new version of the extension should now be available at https://extensions.gnome.org/extension/4413/improved-osk.
As far as I can tell, this change does not impact other major distributions running Gnome, but I might have to revisit this if any issues crop up.

**Comment by itsCryne** [comment]
Thank you. The buttons are now visible
![Screenshot](https://user-images.githubusercontent.com/51213332/144816427-d010eeef-f583-46d2-a012-438b713b839b.png)
