### ISSUE TITLE
No change in keyboard layout

### ISSUE THREAD

**Issue by piegamesde** [nick-shmyrev/improved-osk-gnome-ext#13]
I installed and activated the extension. It does seem to work, although the layout of the OSK is not changed compared to when the extension is disabled. Especially, the additional control keys are missing.

**Comment by nick-shmyrev** [comment]
After enabling extension, you need to either press `Alt + F2` and enter `r` to reload the Gnome shell if you're using X11, or log out and then back in if you're on Wayland.
Let me know if you're still having issues getting the extension to work.

**Comment by piegamesde** [comment]
I'm pretty sure I did some rebooting between tests but will do.

**Comment by ruralTom** [comment]
Same issue on an MS Surface Pro 3 running ubuntu with gnome 40.4.0

**Comment by piegamesde** [comment]
Okay the extension *is* active, as there is a button in the top bar, the settings work and it *does* have an effect: The width limitation seems to work, the layout is different when the extension is enabled. However, no new keys appear

**Comment by nick-shmyrev** [comment]
@piegamesde What distro are you running? What's your gnome version? How is your layout different? Can you post a screenshot of what you're seeing?

**Comment by nick-shmyrev** [comment]
Closing the issue since there was no response for 15 days.

**Comment by piegamesde** [comment]
Arch Linux, GNOME 41.1, Wayland. The only thing that works is the scaling factor from the settings and the top bar. The scaling factor only scales the keyboard, without changing anything else. The keyboard layout is the standard GNOME layout without modifications from the extensions.

**Comment by nick-shmyrev** [comment]
I just tried installing it on Arch with Gnome 41.1 with Wayland, and I could not reproduce your issue. 

![VirtualBox_Arch Linux_19_12_2021_17_56_53](https://user-images.githubusercontent.com/6802396/146693964-42a1cebf-67b7-4cd8-acba-4e08ec32a441.png)

Admittedly, I did not do a fresh install, but instead found some live .iso with Gnome preinstalled and tested with that. Still, I've seen at least two other users that were using this extension on Arch, so it seems this issue is specific to your machine. Do you have any other Gnome extensions enabled that might've interfered with the keyboard?

**Comment by mackdroid** [comment]
having same issueon arch linux

**Comment by nick-shmyrev** [comment]
@mackdroid, is this on a fresh install, or on a system you've been using for a while? What's your Gnome version? Do you have any other extensions that might interfere with the keyboard? If you press `Alt + F2`, enter `lg`, then go to "Extensions" tab and click "Show errors" for Improved OSK, do you see any? Do you see any errors or warnings if you run `journalctl /usr/bin/gnome-shell -f -o cat` and use the keyboard? Anything else you can recommend I do to reproduce this issue?

**Comment by mackdroid** [comment]
ive done some debugging myself and found that i didnt have ibus daemon installed, after installing it, everything works as intended, im running a fresh install yes
![image](https://user-images.githubusercontent.com/68280146/147468905-9f2d7ba0-f7d2-4b53-87fa-1009fa39f5d2.png)
![image](https://user-images.githubusercontent.com/68280146/147468931-aa0286cb-80ee-4e53-8baf-2289ce10b51d.png)
the issue can be reproduced by not having ibus installed, where it would pop a file not found error in journalctl

**Comment by mackdroid** [comment]
please list this dependency somewhere

**Comment by niall83** [comment]
I'm using EndeavourOS (based on Arch). It was working OK but suddenly stopped (the layout didn't change when enabling/disabling this extension although the colour of the space around the keyboard seemed to change).
Installing ibus-daemon as per mackdroid's suggestion resolved the issue for me.

**Comment by piegamesde** [comment]
I can confirm that installing `ibus` resolves the issue for me as well. Please add a run time check that tells users to install that dependency or something.

**Comment by nick-shmyrev** [comment]
@mackdroid thanks for finding the solution! I'll add this to FAQ.
