### ISSUE TITLE
Cant find F10 key

### ISSUE THREAD

**Issue by clamel77** [nick-shmyrev/improved-osk-gnome-ext#14]
Hello I see all F-function keys, except F10.. Is this issue affecting only me?
I'm on arch linux with gnome 41 with wayland
![Screenshot from 2021-11-22 20-58-34](https://user-images.githubusercontent.com/31662954/142928368-55639bea-82d0-4d5b-bc92-ead423977b3c.png)

**Comment by nick-shmyrev** [comment]
Looks like `F10` is still there, on the left of the `F11` key,  but its text did not fit inside the button and was replaced with ellipsis. Here's how it looks on my device:

![Screenshot from 2021-11-22 15-50-02](https://user-images.githubusercontent.com/6802396/142952813-e25abd52-351b-4efe-a69a-df76b41ebc1e.png)

**Comment by clamel77** [comment]
You are right, I increased keyboard size and now keys are all displaying correctly. Thank you very much
