### ISSUE TITLE
Key icons/symbols missing even with ttf-ancient-fonts-symbola isntalled

### ISSUE THREAD

**Issue by smlehbleh** [nick-shmyrev/improved-osk-gnome-ext#17]
All the modifier keys have their icons missing (Apart from return)
Tried installing 'ttf-ancient-fonts-symbola' but it didnt help :(
Stock Ubuntu 20.04 with gnome shell 3.36

**Comment by nick-shmyrev** [comment]
Caused by a fix for #12. Explicitly setting modifier keys background to `#2c2c2c` to have a consistent color across different distros.

**Comment by smlehbleh** [comment]
Just updated, works great now. Quick question, do you know what css selector to use to change the _key-down_ state? The default theme colour for _key-down_ is almost identical to the _key-up_ state

**Comment by nick-shmyrev** [comment]
> Quick question, do you know what css selector to use to change the _key-down_ state?

Good question! Turns out it's an `:active` pseudo-class. So, to change the _key-down_ styling for all keyboard buttons, you'd have to add this to `stylesheet.css`:
```css
#keyboard .keyboard-key:active {
    background-color: red;
}
```
