### ISSUE TITLE
I am using dvorak as language layout. And screen keyboard shows qwerty. Pop-os 20

### ISSUE THREAD

**Issue by IlimbekNarmatov** [nick-shmyrev/improved-osk-gnome-ext#21]

**Comment by nick-shmyrev** [comment]
I'm afraid this is an upstream issue. Gnome's default OSK (on which this extension is based on) only has one layout for EN_US: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/data/osk-layouts/us.json.

If you really need a Dvorak layout, you could try modifying the default one. On Fedora 36 the gresource file with all the OSK layouts is located here: `/usr/share/gnome-shell/gnome-shell-osk-layouts.gresource`. And I found this article on modifying `gresource` files: https://payaljain05.medium.com/how-to-modify-and-zip-back-a-gresource-file-in-ubuntu-18-04-20-04-c6206bf3497b.

**Comment by nick-shmyrev** [comment]
With the recent changes to OSK, making a custom layout should be much easier. You'll need to follow the manual installation process from [README](https://github.com/nick-shmyrev/improved-osk-gnome-ext/blob/master/README.md#from-source-code), but before running `package-extension.sh` you'll have to make changes to your preferred layout (see [osk-layouts](https://github.com/nick-shmyrev/improved-osk-gnome-ext/tree/master/src/data/osk-layouts)), then continue with the installation process.
