### ISSUE TITLE
issues in gnome 42

### ISSUE THREAD

**Issue by mackdroid** [nick-shmyrev/improved-osk-gnome-ext#22]
**Describe the bug**
A. The pull up gesture doesnt work
B. Cannot enter password on polkit prompts

**To Reproduce**
A. Try pulling up from below, should open the osk
B. 1. Open apps that require root and use polkit to get it i.e gparted
    2. Try typing on the osk

**Environment (please complete the following information):**
 - Distro: Arch
 - Gnome version: 42

**Additional context**
Have you been running your system for a while, or is it a fresh installation?
using for quite sometime but its rather minimal
Are you running any other extensions that might interfere with on-screen keyboard?
No
Does `journalctl /usr/bin/gnome-shell -f -o cat` show any errors?
Can you see any errors in looking glass? (Press `Alt + F2`, enter `lg`, switch to "extensions" tab and click "show errors" for Improved OSK extensionr
Nothing relevant

**Comment by notgne2** [comment]
at least the gesture issue seems to be upstream https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5335

**Comment by ruralTom** [comment]
I cannot type into a password field either. Keyboard shows but is unresponsive.

**Comment by jfedyczak** [comment]
The keyboard seems disabled when entering passwords is system modal windows in gnome (e.g. wifi network password). It shows up correctly but does not accept any touch input.

**Comment by nick-shmyrev** [comment]
Resolved upstream.
