### ISSUE TITLE
[Question] How make it work with non Gnome application?

### ISSUE THREAD

**Issue by stormenergy91** [nick-shmyrev/improved-osk-gnome-ext#23]
The keyboard show up on all Gnome applications (Ubuntu 22.04 - Gnome 42) but it never show up with all other application, like Firefox. So I cannout use linux with my Surface with out phisical keyboard.

There is a way to show the keyboard up on this ohter app? 

Like in Windows, is possible to add an keyboard button in the right top corner  so there is always the possibilità to call the keyboard without a touch input?

Thanks

**Comment by RichardJActon** [comment]
Hi @stormenergy91 You can get a button in the statusbar to manually show the OSK with the "Show statusbar icon" setting in improved OSK's settings in the extension manager. (You probably figured this out by now given the age of your issue but for the benefit of anyone asking the same Q who stumbles across this in search)

(See also issues #25 & #28)

**Comment by nick-shmyrev** [comment]
You can also swipe up from the bottom of the screen to bring the OSK up.
Not an issue, closing.
