### ISSUE TITLE
Disturbs the mouse icon location in non-snap software

### ISSUE THREAD

**Issue by Bushido1** [nick-shmyrev/improved-osk-gnome-ext#31]
**Describe the bug**
Clicking on a website elements (buttons, places where text can be inserted) is disturbed. 

**To Reproduce**
1. Go to whichever website with Brave Browser (downloaded from their official website).
2. Click on whichever button on whatever website.

**Expected behavior**
The button or other clickable element should be selected and/or become available/focused. Instead, website reacts like I have clicked on something else, rather on the needed button. Seems like the on-screen keyboard moves the website up or down instead focusing a mouse click on a place what I have clicked.

**Screenshots**

**Environment (please complete the following information):**
 - Distro: Ubuntu 22.04.1 LTS
 - Gnome version: 42.4
 - 
**Additional context**
System is a fresh installation.
No other extension is interfering with on-screen keyboard.
Does `journalctl /usr/bin/gnome-shell -f -o cat` show any errors?
`(../clutter/clutter/clutter-actor.c:12430):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
(../clutter/clutter/clutter-actor.c:12430):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
(../clutter/clutter/clutter-actor.c:12430):clutter_actor_event: runtime check failed: (retval == CLUTTER_EVENT_PROPAGATE)
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Ignored exception from dbus method: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownInterface: Object does not implement the interface
Window manager warning: last_focus_time (337608) is greater than comparison timestamp (380).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: last_user_time (337608) is greater than comparison timestamp (380).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW.  Trying to work around...
Window manager warning: W12 appears to be one of the offending windows with a timestamp of 337608.  Working around...
Window manager warning: W0 appears to be one of the offending windows with a timestamp of 310923.  Working around...
`
Can you see any errors in looking glass? No

**Comment by nick-shmyrev** [comment]
Could not reproduce with Ubuntu 22.04 with ghome-shell 42.4.
What do you mean by "disturbed"? Please describe in more details what you're seeing, or better yet take a screenshot, or record a gif/video.

The only thing I did see is that OSK wasn't showing up when you tap on input fields. But it behaves the same way with the original Gnome OSK, so it's likely an issue with Brave not implementing/emitting some Gnome event when the user taps on a text input.

**Comment by Bushido1** [comment]
By "disturbed" I mean that when I try to select a text for coping, 
another element or text of website is selected/copied.

**Comment by nick-shmyrev** [comment]
This extension does not interact with copy, paste or text selection functions in any way.
Do you see the same issue when using the original Gnome OSK? Are you using Brave's own copy/paste buttons? If so, that's a Brave issue, please report it in their repo/issue tracker.
