### ISSUE TITLE
Unable to install on Gnome 43

### ISSUE THREAD

**Issue by ShaunTheSalvo** [nick-shmyrev/improved-osk-gnome-ext#37]
**What is happening**

**_Unable to install extension._** Accessing the extension under Gnome 43 at https://extensions.gnome.org/extension/4413/improved-osk/ - extension is marked as "Incompatible".

Issue seems to be due to change to `metadata.json` file. Appears this file has been modified (and modified version uploaded to [extensions.gnome.org](url)) since the email notifying issue #30 was sent.

**More information**
I installed the extension via https://extensions.gnome.org/extension/4413/improved-osk/ earlier this morning. The extension installed, could be activated, and worked without issue. About half an hour ago, I attempted to reinstall the extension in the same way (I had to roll back my system to a snapshot from yesterday, due to an unrelated issue). When attempting to install Improved OSK via https://extensions.gnome.org/extension/4413/improved-osk/, the extension was marked as "INCOMPATIBLE" on the website.

I noted the only file that has been modified on Github between the two attempts at installing was `metadata.json`; I **am assuming the issue has to do with the Gnome version in this file**. Unfortunately, I don't have a copy of the installed version of the extension from earlier today to verify this.

**Environment:**
 - Distro: Arch Linux (installed from official Arch ISO)
 - Gnome version: 43 (Wayland)

**Additional context**
_Have you been running your system for a while, or is it a fresh installation?_  System has been running for roughly a month.

_Are you running any other extensions that might interfere with on-screen keyboard?_ None that I am aware of (see above re two installations of Improved OSK extension).

_Does `journalctl /usr/bin/gnome-shell -f -o cat` show any errors?_
> Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
>   _onMountAdded@resource:///org/gnome/shell/ui/components/autorunManager.js:146:24
> 
> Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
>   _onMountAdded@resource:///org/gnome/shell/ui/components/autorunManager.js:146:24
> 
> GNOME Shell started at Sat Mar 11 2023 19:35:38 GMT+1000 (Australian Eastern Standard Time)
> Registering session with GDM
> Error connecting to the screencast service
> activated: Extensions
> Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400004
> Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400004
> clutter_actor_set_child_below_sibling: assertion 'sibling->priv->parent == self' failed
> Starting ddterm app: ["/usr/share/gnome-shell/extensions/ddterm@amezin.github.com/com.github.amezin.ddterm","--undecorated"]
_(Note: I do not believe this output to be relevant, as at present Improved OSK extension is not installed on my system, and cannot be installed.)_

_Can you see any errors in looking glass? (Press `Alt + F2`, enter `lg`, switch to "extensions" tab and click "show errors" for Improved OSK extension):_ No, as extension not currently installed

Happy to continue testing, or assisting in any way I can.

**Comment by nick-shmyrev** [comment]
I had to take down version 11 that was released yesterday. It was targeting older Gnome versions, with which it is no longer compatible with. Version 12 only targets Gnome 43, has passed code review a few hours ago, and is now available at https://extensions.gnome.org/extension/4413/improved-osk/.
