### ISSUE TITLE
Hungarian layout missing extended keys

### ISSUE THREAD

**Issue by horvathcsabalaszlo** [nick-shmyrev/improved-osk-gnome-ext#42]
**Describe the bug**
The built-in Gnome OSK comes up even if the built-in is turned off

**To Reproduce**
Install Debian Testing and the extension, turn it on :) 

**Expected behavior**
I need to use the extension, with the improved keyboard.

**Screenshots**
https://ibb.co/F3WMCvt
https://ibb.co/4mHq46L

**Environment (please complete the following information):**
 - Distro: Debian Bookworm
 - Gnome version: 43.3

**Additional context**
Fresh install of extension, otherwise Gnome and Debian is not old and not much used. Builtin OSK works well, but it's difficult to use terminal with it :D

**Comment by nick-shmyrev** [comment]
Tried installing Improved OSK in Debian Bookworm (gnome-shell 43.3) VM, and everything worked fine.

![image](https://user-images.githubusercontent.com/6802396/227020430-f1410fcf-db93-4418-bf0b-07c174dc2d13.png)

I suspect the issue might actually be with the OSK layout you're using (looks like one of the Eastern European languages, but I'm not sure which one). If you're using one of the layouts I haven't updated, it'll look like the default Gnome OSK. Can you see the extended keys if you switch to one of the supported layouts (there's a list [here](https://github.com/nick-shmyrev/improved-osk-gnome-ext#improved-osk-gnome-ext))?

If your preferred layout is not in this list, let me know which one you're using, and I'll update it. Or you can take a look at how one of the supported layouts were updated [here](https://github.com/nick-shmyrev/improved-osk-gnome-ext/tree/master/src/data/osk-layouts), and make a PR with the changes yourself.

**Comment by horvathcsabalaszlo** [comment]
Hi,

Thanks! 
I was set up for Hungarian, and yes, as i switched to US, the full keyboard comes up, like on your screenshot. And in fact it can write the special Hungarian characters (long press on e, a, o, or i) , so i'm OK with this :) 
So thanks for your support :)

Do you know how to configure the built-in keyboard? :D I'm just curious, because i Googled for some days and didn't find anything :D

**Comment by nick-shmyrev** [comment]
No worries! I've added the extended keys to Hungarian layout. It wasn't that hard, the only reason it wasn't included in the first place is because there are 60 different layouts in Gnome and I didn't have time to convert them all.

You'll have to do a manual installation if you want to use Hungarian layout right now. I still need to make some changes to pass the code review before I can publish the updated version to [extensions.gnome.org](https://extensions.gnome.org/).

I don't think the built-in Gnome keyboard is configurable at all... What did you want to configure there?

**Comment by horvathcsabalaszlo** [comment]
Yes, i know that there are much more than easy to handle languages and layouts :D So it's not a problem that you haven't got time for it. 

Will test the layout as i can :)

Wanted to config : exactly the layout or to set in which layout is used for terminal, or so. 
I wonder that the built-in keyboard is so hardcoded... In Linux, almost everything is changeable :)

**Comment by nick-shmyrev** [comment]
Yeah, there is no way to select a specific language/layout for terminal in Gnome's built-in OSK, it is hard-coded to switch to `us-extended` if you focus on a terminal window.

Thankfully, recently there was a [PR](https://github.com/nick-shmyrev/improved-osk-gnome-ext/pull/36) that disabled switching to `us-extended` layout in terminal window, so you should be able to use any layout you want in terminal with this extension.

**Comment by horvathcsabalaszlo** [comment]
But it did not do the switch :D The minimal set came up everywhere... was frustrating :D
