### ISSUE TITLE
Question: Why is it not working. I am on Gnome 43.4 and setup ibus

### ISSUE THREAD

**Issue by FearlessSpiff** [nick-shmyrev/improved-osk-gnome-ext#48]
Hi. I am out of knowledge. I wanted to use your extension on a Arch-Gnome install on my SteamDeck but can"t make it to pop up.
* I installed the extension
* I can configure it and it is enabled
* I enabled ibus for my user (see below)
* The old OSK is shown when I open it or when it gets automatically opened

Where could I check what is going wrong?
Thanks a lot!

Here my running ibus:
```
systemctl status --user ibus@\:0.service 
● ibus@:0.service - Intelligent Input Bus
     Loaded: loaded (/usr/lib/systemd/user/ibus@.service; enabled; preset: enabled)
     Active: active (running) since Tue 2023-04-18 07:38:02 CEST; 5h 7min ago
       Docs: man:ibus-daemon(1)
   Main PID: 1009 (ibus-daemon)
      Tasks: 9 (limit: 17750)
     Memory: 7.1M
        CPU: 170ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-ibus.slice/ibus@:0.service
             ├─1009 /usr/bin/ibus-daemon --replace --xim
             └─1037 /usr/lib/ibus/ibus-dconf
```

**Comment by nick-shmyrev** [comment]
The issue might be with the keyboard layout you're using: https://github.com/nick-shmyrev/improved-osk-gnome-ext#my-language-layout-doesnt-have-the-additional-keys.
Can you see additional keys if you switch to English keyboard layout? You can add other language layouts if you go to **Settings -> Keyboard -> Input Source**.
If you can see extra keys in English (US) layout, that means I haven't updated your language layout yet. Let me know what language you're using, and I'll add the extra keys to it too. Or, feel free to add them yourself and make a PR. Here's an [example](https://github.com/nick-shmyrev/improved-osk-gnome-ext/commit/907da2b70c3d9a2aca363ceafc6a778c49c5994c) of what I did to update Hungarian layout.
If that doesn't help, check `journalctl` for any gnome-shell errors:
```
journalctl /usr/bin/gnome-shell -f -o cat
```

**Comment by FearlessSpiff** [comment]
Thanks. I use DE layout which should be supported. I tried with EN, but still the same. When I check `journalctl -f -o cat`I can see this line whether I enable or disable the extension:
`Tried to remove not registered resource`
What is funny, when I disable my working Clippboar-History extension I can also see this. But not when enabling it.

**Comment by FearlessSpiff** [comment]
Ah funny. Now I resized the Landscape height and it somehow activated I think. It gets bigger. But not filling the whole area. 
This is at 33%:
![image](https://user-images.githubusercontent.com/1927259/232862486-4e61c38a-2aef-4f3c-ada3-d5a5069c3e2a.png)

And this at 50%:
![image](https://user-images.githubusercontent.com/1927259/232863077-dd491d77-eab7-4466-807b-9fffaaba3360.png)

I guess with 50% it is already much better!
