### ISSUE TITLE
Updated to newest version out today supporting gnome 44 and still isn't working

### ISSUE THREAD

**Issue by clabbin** [nick-shmyrev/improved-osk-gnome-ext#50]
I'm on a fresh install of Fedora 38 an have today's Improved OSK update supporting gnome 44 installed and the extension refuses to work no matter what I try with any of the extension settings or system settings. Any ideas?

**Comment by nick-shmyrev** [comment]
Check if the system has disabled all user extensions. There's a toggle that does that at https://extensions.gnome.org/local/, or you can run `gsettings set org.gnome.shell disable-user-extensions false` in the terminal to enable everything again.
Also, I know how it sounds, but try logging out and back into the system after you've installed/enabled the extension and see if it works after that.

If those 2 things made no difference, some follow-up questions:

- Can you see the extension icon in the taskbar?
- Are you using one of the supported language layouts (see [here](https://github.com/nick-shmyrev/improved-osk-gnome-ext#improved-osk-gnome-ext))? If not, let me know which language you're using, and I'll add it.
- Does it show in the list of extensions when you run `gnome-extensions list` in the terminal?
- Does `journalctl /usr/bin/gnome-shell -f -o cat` show any errors?
- Can you see any errors in Looking Glass? (Press Alt + F2, enter `lg`, switch to "extensions" tab and click "show errors" for Improved OSK extension).
- How did you install the extension?

**Comment by clabbin** [comment]
Yeah just using english as the language. Here's what terminal spits out:
gnome-extensions list
apps-menu@gnome-shell-extensions.gcampax.github.com
background-logo@fedorahosted.org
launch-new-instance@gnome-shell-extensions.gcampax.github.com
places-menu@gnome-shell-extensions.gcampax.github.com
window-list@gnome-shell-extensions.gcampax.github.com
improvedosk@nick-shmyrev.dev
[surstu@surfedora ~]$ journalctl /usr/bin/gnome-shell -f -o cat
== Stack trace for context 0x558eae8ba340 ==
#0   558eb2bcfda8 i   resource:///org/gnome/shell/ui/windowPreview.js:571 (2c85e35c1470 @ 77)
Object St.Label (0x558eb160bcf0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_windowPreview_WindowPreview (0x558eb02902e0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Tried to remove not registered resource
JS ERROR: Error: Argument descendant may not be null
_onCapturedEvent@resource:///org/gnome/shell/ui/keyboard.js:232:24

meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
/

**Comment by nick-shmyrev** [comment]
After enabling the extension, try logging out of the system, then logging back in to restart the Gnome Shell. Doing a full reboot also works.
I should also mention that I've enabled the "Screen Keyboard" in Accessibility Settings to get the keyboard to show up on a system without a touchscreen, but since you're already seeing the default OSK, this shouldn't be the issue.

I've tested it in Fedora 38 (both live env., and a full install) with version 15 of this extension, and installed from [extensions.gnome.org](https://extensions.gnome.org/extension/4413/improved-osk/). It worked fine:
![image](https://user-images.githubusercontent.com/6802396/233792201-de942c8d-fe37-49f6-a6d2-8971ee83a049.png)

**Comment by clabbin** [comment]
I don't know what I did or maybe didn't do to fix it but I had already tried all of that (logging in and out, restarting) stuff yesterday and when I turned my computer back on this morning to mess with it, it's just working.... Well in any case, I really appreciate you taking the time to help figure it out and definitely appreciate you maintaining this project!! :)
