### ISSUE TITLE
Additional buttons don't appear on Polish keyboard layout

### ISSUE THREAD

**Issue by lukasaristide** [nick-shmyrev/improved-osk-gnome-ext#52]
**Describe the bug**
While English(UK) keyboard works OK, Polish keyboard does not have additional buttons (Ctrl, Alt, Esc etc.).
This is the only way I could make them appear:
https://github.com/lukasaristide/improved-osk-gnome-ext/commit/681817e4194178cf205c7a33aed871898410f3f1
though I suppose this is not the desired way - since this is not how it's done for other keyboard layouts.

**Environment (those are the ones I verified):**
 - Distro: Fedora 38, Ubuntu 23.04, Ubuntu 22.10
 - Gnome version: 43, 44

**Comment by nick-shmyrev** [comment]
> This is the only way I could make them appear: [lukasaristide@681817e](https://github.com/lukasaristide/improved-osk-gnome-ext/commit/681817e4194178cf205c7a33aed871898410f3f1) though I suppose this is not the desired way - since this is not how it's done for other keyboard layouts.

Great job, that looks nice! I'm actually considering bringing back "Super" key (related #43), so I'd be happy to merge this in if you'd like to make a PR.

Lowercase
![image](https://user-images.githubusercontent.com/6802396/234889119-099f7372-99ed-40f4-8af5-d0dddf83ab78.png)

Uppercase
![image](https://user-images.githubusercontent.com/6802396/234889288-41387f73-46cb-4fce-b6b4-0d332b911b66.png)


Just a few nitpicks in case you do turn this into a PR:

- "Super" key should be present both in lowercase and uppercase layers
- I was thinking of adding "Super" key between "?123" and "Alt" keys, as this is where it's usually located on physical keyboards. Is there any particular reason you prefer to add it after "Alt"?

**Comment by lukasaristide** [comment]
Sure, I have created it - also, moved the Super key to its rightful place and added it to uppercase set too.
