### ISSUE TITLE
Provide soft keyboard without Gnome?

### ISSUE THREAD

**Issue by rbreaves** [nick-shmyrev/improved-osk-gnome-ext#56]
I have not delved into the source, but what is the likelihood of breaking this out of the dependencies of Gnome? I think this would be far better if it were independent of the DE entirely.

**Comment by Vishram1123** [comment]
The problem with GNOME is that Mutter has no support for Wayland's Layer_Shell protocol (see [here](https://gitlab.gnome.org/GNOME/mutter/-/issues/1922)), so the keyboard has to be tightly integrated with GNOME. In fact, this extension is simply extending and modifying the existing OSK's functionality, so it isn't really possible to break the keyboard free of GNOME.

**Comment by nick-shmyrev** [comment]
Like @Vishram1123 said, this extension is based on the built-in Gnome OSK. It's basically a set of patches on top of it.
So no, there won't be a standalone version.
