### ISSUE TITLE
The default portrait height looks too high

### ISSUE THREAD

**Issue by SamLukeYes** [nick-shmyrev/improved-osk-gnome-ext#9]
![2021-06-21 21-22-33屏幕截图](https://user-images.githubusercontent.com/12882091/122769770-6f2db480-d2d7-11eb-8641-04e5d5fd15e9.png)
There's a lot of unused space above the keys with the default height 33 on portrait screen, while 16 looks fine for me. Should the default value be decreased?

**Comment by nick-shmyrev** [comment]
That's a good point, it's unlikely there's a device where 33% keyboard height would look good in portrait mode. :+1: 
I'll set the default height to 16% in portrait mode.
